/**
 * @file twic_interface_fid.h
 * @brief a header file for TZ10xx TWiC for Bluetooth 4.0/4.1 Smart
 * @version V1.2.0
 * @note
 */

/*
 * COPYRIGHT (C) 2014-2017
 * TOSHIBA CORPORATION STORAGE & ELECTRONIC DEVICES SOLUTIONS COMPANY
 *
 * This software is released under the MIT License.
 * http://opensource.org/licenses/mit-license.php
 */

#ifndef _TWIC_INTERFACE_FID_H_
#define _TWIC_INTERFACE_FID_H_

/*
 * TWiC INTERFACE API INDEX. (DO NOT Change the order.)
 *
 */

enum {
/* API1 */
  TWIC_API1_IDX,
  TWIC_LEREADLOCALVERSIONINFORMATION,
  TWIC_LECEPATCHBASE,
  TWIC_LECEPATCHWRITE,
  TWIC_LECEPATCHCONTROL,
  TWIC_LECEDBUSWRITE,
  TWIC_LECEDBUSREAD,
  TWIC_LECEMEMORYWRITE,
  TWIC_LECEMEMORYREAD,
  TWIC_LECEXOSCTRIMING,
  TWIC_LECESETTXPOWER,
  TWIC_LECEREADFWVER,
  TWIC_LECESETBAUDRATE,
  TWIC_LEREADBDADDR,
  TWIC_LECEFLOWCONTROL,
  TWIC_LECEHOSTDELAY,
  TWIC_LEWRITEBDADDR,
  TWIC_LECELOWPOWERCLOCKSETUP,
  TWIC_LECELOWPOWERPRIMARYSETUP,
  TWIC_LECELOWPOWERCONTROLPINSETUP,
  TWIC_LECELOWPOWERDISCOVERABLESETUP,
  TWIC_LECECHANGETOCM, /* 21 */

  TWIC_LEINITIALIZEDEVICE,
  TWIC_LEGATTSERVERSTART,
  TWIC_LEGATTCLIENTSTART, /* 24 */

  TWIC_LECELOWPOWERMODE,
  TWIC_LEDISCOVERABLE,
  TWIC_LESTOPADVERTISING, /* 27 */

  TWIC_LESMSETIRVALUE, /* 28 */
  TWIC_LESMENCRYPT,
  TWIC_LESMMASPAIRINGREQUEST,
  TWIC_LESMSLVPAIRINGCONFIRM,
  TWIC_LESMSLVPAIRINGFAILED,
  TWIC_LESMSLVSECURITYREQUEST,
  TWIC_LESMMASSECURITYREJECT,
  TWIC_LESMMASPAIRINGFAILED, /* 35 */

  TWIC_LESMMASKBPASSKEYREPLY, /* 36 */
  TWIC_LESMSLVKBPASSKEYREPLY,
  TWIC_LESMSLVKBPASSKEYNEGATIVEREPLY,
  TWIC_LESMMASKBPASSKEYNEGATIVEREPLY,
  TWIC_LESMMASDPPASSKEYREPLY,
  TWIC_LESMMASDPPASSKEYNEGATIVEREPLY,
  TWIC_LESMSLVDPPASSKEYREPLY,
  TWIC_LESMSLVDPPASSKEYNEGATIVEREPLY,
  TWIC_LESMMASSTARTENCRYPTION,
  TWIC_LESMMASOOBTKREPLY,
  TWIC_LESMMASOOBTKNEGATIVEREPLY,
  TWIC_LESMSLVOOBTKREPLY,
  TWIC_LESMSLVOOBTKNEGATIVEREPLY,
  TWIC_LESMMASBONDINGINFORMATIONREPLY,
  TWIC_LESMMASBONDINGINFORMATIONNEGATIVEREPLY,
  TWIC_LESMSLVBONDINGINFORMATIONREPLY,
  TWIC_LESMSLVBONDINGINFORMATIONNEGATIVEREPLY,
  TWIC_LESMMASBONDINGSTATE,
  TWIC_LESMSLVBONDINGSTATE, /* 54 */

  TWIC_LESETADVERTISINGDATA, /* 55 */
  TWIC_LEREADTXPOWERLEVEL,
  TWIC_LEREADRSSI,
  TWIC_LEREADREMOTEVERSION,
  TWIC_LELMGENRESOLVABLEBDADDR,
  TWIC_LELMRESOLVEBDADDR,
  TWIC_LESETRANDOMADDRESS, /* 61 */
  TWIC_LEREADLOCALSUPPORTEDFEATURES,
  TWIC_LESETHOSTCHANNELCLASSIFICATION,
  TWIC_LEREADCHANNELMAP,
  TWIC_LEREADSUPPORTEDSTATES,
  TWIC_LEREADREMOTEUSEDFEATURES,
  TWIC_LEREADWHITELISTSIZE,
  TWIC_LEADDWHITELIST,
  TWIC_LEDELWHITELIST,
  TWIC_LESETSCANENABLE,
  TWIC_LESETSCANDISABLE, /* 72 */
  TWIC_LECLEAREWHITELIST,
  TWIC_LEDISCONNECT,
  TWIC_LECONNECTIONUPDATE,
  TWIC_LECEL2CAPSIGNALACCEPTCONNECTIONUPDATE,
  TWIC_LECEL2CAPSIGNALREJECTCONNECTIONUPDATE,
  TWIC_LECONNECTIONPARAMETERREQUESTREPLY,
  TWIC_LECONNECTIONPARAMETERREQUESTNEGATIVEREPLY,
  TWIC_LECREATECONNECTION,
  TWIC_LECREATECONNECTIONCANCEL, /* 80 */

  TWIC_GATTNOTIFICATION, /* 81 */
  TWIC_GATTINDICATION,
  TWIC_GATTSERVERWRITECHARACTERISTICS,
  TWIC_GATTSERVERWRITEDESCRIPTOR,
  TWIC_GATTSERVEREXGMTURESPONSE,
  TWIC_GATTSERVERCHARDESPWRITEINRESPONSE,
  TWIC_GATTSERVERCHARDESPREADOUTRESPONSE,
  TWIC_GATTSERVERCHARVALREADOUTRESPONSE,
  TWIC_GATTSERVERCHARVALMULTIREADOUTRESPONSE,
  TWIC_GATTSERVERCHARVALWRITEINRESPONSE,
  TWIC_GATTSERVERLONGCHARVALREADOUTRESPONSE,
  TWIC_GATTSERVERLONGCHARDESPREADOUTRESPONSE,
  TWIC_GATTSERVERLONGCHARVALPREPAREWRITEINRESPONSE,
  TWIC_GATTSERVERLONGCHARDESPPREPAREWRITEINRESPONSE,
  TWIC_GATTSERVEREXECCHARVALWRITEINRESPONSE,
  TWIC_GATTSERVEREXECCHARDESPWRITEINRESPONSE, /* 95 */

  TWIC_GATTCLIENTEXGMTU, /* 96 */
  TWIC_GATTCLIENTDISCOVERPRIMARYSERVICE,
  TWIC_GATTCLIENTDISCOVERPRIMARYSERVICEBYSERVICEUUID,
  TWIC_GATTCLIENTFINDINCLUDEDSERVICE,
  TWIC_GATTCLIENTDISCOVERALLCHARACTERISTICS,
  TWIC_GATTCLIENTDISCOVERCHARACTERISTICSBYUUID,
  TWIC_GATTCLIENTDISCOVERALLDESCRIPTORS,
  TWIC_GATTCLIENTREADCHARACTERISTICVALUE,
  TWIC_GATTCLIENTREADUSINGCHARACTERISTICUUID, /* 105 */
  TWIC_GATTCLIENTWRITECHARACTERISTICVALUE,
  TWIC_GATTCLIENTREADCHARACTERISTICDESCRIPTOR,
  TWIC_GATTCLIENTWRITECHARACTERISTICDESCRIPTOR,
  TWIC_GATTCLIENTINDICATIONCONFIRMATIONRESPONSE,
  TWIC_GATTCLIENTWRITEWITHOUTRESPONSE,
  TWIC_GATTCLIENTSIGNEDWRITEWITHOUTRESPONSE,
  TWIC_GATTCLIENTREADMULTIPLECHARVALUES,
  TWIC_GATTCLIENTRELIABLEWRITE,
  TWIC_GATTCLIENTREADLONGCHARACTERISTICVALUE,
  TWIC_GATTCLIENTREADLONGCHARACTERISTICDESCRIPTOR, /* 114 */
  TWIC_GATTCLIENTWRITELONGCHARACTERISTICVALUE,
  TWIC_GATTCLIENTWRITELONGCHARACTERISTICDESCRIPTOR, /* 116 */

/* API2 */
  TWIC_API2_IDX,
  TWIC_LEGATTDBBEGINSERVICECREATION, /* 118 */
  TWIC_LEGATTDBBEGINSECONDARYSERVICECREATION,
  TWIC_LEGATTDBINCLUDESERVICECREATION,
  TWIC_LEGATTDBADDCHARACTERISTICS,
  TWIC_LEGATTDBSETCHARACTERISTICS,
  TWIC_LEGATTDBUPDCHARACTERISTICS,
  TWIC_LEGATTDBSETDESCRIPTOR,
  TWIC_LEGATTDBENDSERVICECREATION,
  TWIC_LEGATTDBSETPERMISSIONS,
  TWIC_LEGATTDBGETPERMISSIONS, /* 127 */
  TWIC_LEGATTDBUPDCHARACTERISTICSVL,
  TWIC_LEGATTDBSETCHARACTERISTICSVL,
  TWIC_LEGATTDBSETDESCRIPTORVL, /* 130 */

/* API3 */
  TWIC_API3_IDX,

  TWIC_API_USER_IDX
};

#define TWIC_LESMMASKBPASSKEYENTRYREPLY TWIC_LESMMASKBPASSKEYREPLY
#define TWIC_LESMSLVKBPASSKEYENTRYREPLY TWIC_LESMSLVKBPASSKEYREPLY
#define TWIC_LESMSLVKBPASSKEYENTRYNEGATIVEREPLY \
  TWIC_LESMSLVKBPASSKEYNEGATIVEREPLY
#define TWIC_LESMMASKBPASSKEYENTRYNEGATIVEREPLY \
  TWIC_LESMMASKBPASSKEYNEGATIVEREPLY
#define TWIC_LESMMASDPPASSKEYENTRYREPLY TWIC_LESMMASDPPASSKEYREPLY
#define TWIC_LESMMASDPPASSKEYENTRYNEGATIVEREPLY \
  TWIC_LESMMASDPPASSKEYNEGATIVEREPLY
#define TWIC_LESMSLVDPPASSKEYENTRYREPLY TWIC_LESMSLVDPPASSKEYREPLY
#define TWIC_LESMSLVDPPASSKEYENTRYNEGATIVEREPLY \
  TWIC_LESMSLVDPPASSKEYNEGATIVEREPLY

#endif /* _TWIC_INTERFACE_FID_H_ */
